### ISSUE TITLE
Access Denied - When creating repo with attached "Upstreams"

### ISSUE THREAD

**Issue by waderobson** [aws-cloudformation/aws-cloudformation-resource-providers-codeartifact#36]
**Describe the issue**
Ran into problems linking to an upstream repo created within the same stack. I remove the `Upstreams` section of the template things deploy fine.  

To troubleshoot I edited the `repository-resource-execution-role` to have `codeartifact:*` - no change

**To Reproduce**
1 . Deploy this template - observe `Access denied for operation 'codeartifact:CreateRepository'` error
```
Parameters:
  DomainName:
    Type: String
  RepoName:
    Type: String
Resources:
  CodeArtifactDomain:
    Type: AWSdevToolsBeta::CodeArtifact::Domain
    Properties:
      DomainName:
        Ref: DomainName
  PypiUpstreamRepository:
    DependsOn: CodeArtifactDomain
    Type: AWSdevToolsBeta::CodeArtifact::Repository
    Properties:
      RepositoryName: pypi-store
      DomainName:
        Ref: DomainName
      ExternalConnections:
       - public:pypi
  CodeArtifactRepository:
    DependsOn: PypiUpstreamRepository
    Type: AWSdevToolsBeta::CodeArtifact::Repository
    Properties:
      RepositoryName:
        Ref: RepoName
      DomainName:
        Ref: DomainName
      Upstreams:
       - pypi-store

```
2. Comment out upstream and redeploy. 

**Expected behavior**
Successful deployment

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/1497790/92976256-06a7d200-f43f-11ea-8554-f1e4f0b69ea6.png)
